### ISSUE TITLE
Unify file search methods to doublestar + "!" + "#"

### ISSUE THREAD

**Issue by suzuki-shunsuke** [lintnet/lintnet#85]
https://github.com/bmatcuk/doublestar

Simplify the config.

Before

```yaml
targets:
  - lint_files:
      search_type: equal
      paths:
        - path: lintnet/csv.jsonnet
```

After

```yaml
targets:
  - lint_files: |
      lintnet/csv.jsonnet
    modules: |
      toml:lintnet/csv.jsonnet
    imports: |
      utils.libsonnet:suzuki-shunsuke/lintnet-example-2:util.libsonnet
    data_files: |
      examples/hello.csv
```
